version: "3.5"

networks:
    front-end:
    mining:
    back-end:

services:
    rng:
        image: sanchitd9/rng:v1
        networks:
            - mining
        deploy:
            mode: global

    hasher:
        image: sanchitd9/hasher:v1
        networks:
            - mining

    worker:
        image: sanchitd9/worker:v1
        networks:
            - mining
            - back-end
        deploy:
            replicas: 3

    webui:
        image: sanchitd9/webui:v1
        networks:
            - front-end
            - back-end
        ports:
            - target: 80
              published: 8000

    redis:
        image: redis
        networks:
            - back-end
